export const theme = {
  sansSerif: '"objektiv-mk3", -apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, Helvetica, "Helvetica Neue", Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif',
  sansSerifDisplay: '"objektiv-mk1", -apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, Helvetica, "Helvetica Neue", Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif',
  serif: '"bressay", Georgia, Times, "Times New Roman", serif',
  serifDisplay: '"bressay-display", Baskerville, "Baskerville Old Face", "Hoefler Text", Garamond, "Times New Roman", serif',
  code: '"source-code-pro", Consolas, Monaco, monospace',

  fontSize1: '4rem',
  fontSize2: '3rem',
  fontSize3: '1.875rem',
  fontSize4: '1.25rem',
  fontSize5: '1.125rem',
  fontSize6: '1rem',

  lineHeightSolid: '1',
  lineHeightCopy: '1.5',

  spacingExtraSmall: '0.25rem',
  spacingSmall: '0.5rem',
  spacingSmallMedium: '0.75rem',
  spacingMedium: '1rem',
  spacingMediumLarge: '1.5rem',
  spacingLarge: '2rem',
  spacingExtraLarge: '4rem',
  spacingExtraExtraLarge: '8rem',
  spacingExtraExtraExtraLarge: '16rem',

  siteMaxWidth: '100rem',

  black: '#000',
  nearBlack: '#222324',
  darkGray: '#434547',
  midGray: '#5b5e61',
  gray: '#606366',
  silver: '#909499',
  lightSilver: '#aaa',
  moonGray: '#ccc',
  lightGray: '#dcdee0',
  nearWhite: '#f5f7fa',
  white: '#fff',

  darkBlue: '#00449e',
  blue: '#0779fa',
  lightBlue: '#96ccff',
  lightestBlue: '#cdecff',
  washedBlue: '#f6fffe',
}
