export const theme = {
  sansSerif: '"objektiv-mk3", -apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, Helvetica, "Helvetica Neue", Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif',
  sansSerifDisplay: '"objektiv-mk1", -apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, Helvetica, "Helvetica Neue", Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif',
  serif: '"bressay", Georgia, "Times New Roman", Times, serif',
  serifDisplay: '"bressay-display", Baskerville, "Baskerville Old Face", "Hoefler Text", Garamond, "Times New Roman", serif',
  code: '"source-code-pro", SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',

  fontSize1: '4rem',
  fontSize2: '3rem',
  fontSize3: '1.875rem',
  fontSize4: '1.5rem',
  fontSize5: '1.25rem',
  fontSize6: '1.125rem',
  fontSize7: '1rem',
  fontSize8: '0.9375rem',
  fontSizeCopy: '1.375rem',
  fontSizeLead: '1.75rem',

  lineHeightSolid: '1',
  lineHeightCopy: '1.5',

  tracked: '0.125rem',

  spacingExtraSmall: '0.25rem',
  spacingSmall: '0.5rem',
  spacingSmallMedium: '0.75rem',
  spacingMedium: '1rem',
  spacingMediumLarge: '1.5rem',
  spacingLarge: '2rem',
  spacingExtraLarge: '3rem',
  spacingExtraExtraLarge: '4rem',
  spacingExtraExtraExtraLarge: '6rem',

  siteMaxWidth: '100rem',

  // black: '#000',
  nearBlack: '#222324',
  darkGray: '#434547',
  midGray: '#5b5e61',
  gray: '#606366',
  silver: '#909499',
  // lightSilver: '#aaa',
  moonGray: '#cdcfd1',
  lightGray: '#dcdee0',
  lightestGray: '#edf0f2',
  nearWhite: '#f5f7fa',
  white: '#fff',

  darkBlue: '#0660c7',
  blue: '#0779fa',
  lightBlue: '#6baefa',
  lightestBlue: '#e1edfa',
  washedBlue: '#f5faff',
}
